// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJYDTDrAHOKBtVVV18bO4C8ubDfyRylRY',
    appId: '1:756197314313:web:4a7974966daa9e2f7b8dd8',
    messagingSenderId: '756197314313',
    projectId: 'smarthomz-49270',
    authDomain: 'smarthomz-49270.firebaseapp.com',
    storageBucket: 'smarthomz-49270.appspot.com',
    measurementId: 'G-RXPLRJ92KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFEqI9Tr1ZRlwGvMLqadgvF0VIXkgiC-M',
    appId: '1:756197314313:android:32b176d51a68998e7b8dd8',
    messagingSenderId: '756197314313',
    projectId: 'smarthomz-49270',
    storageBucket: 'smarthomz-49270.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAohQAljaWPwWnf-y2qY1pGsSuwLwc-D4Y',
    appId: '1:756197314313:ios:2f7a43a08fd669957b8dd8',
    messagingSenderId: '756197314313',
    projectId: 'smarthomz-49270',
    storageBucket: 'smarthomz-49270.appspot.com',
    iosBundleId: 'com.example.smarthomz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAohQAljaWPwWnf-y2qY1pGsSuwLwc-D4Y',
    appId: '1:756197314313:ios:2f7a43a08fd669957b8dd8',
    messagingSenderId: '756197314313',
    projectId: 'smarthomz-49270',
    storageBucket: 'smarthomz-49270.appspot.com',
    iosBundleId: 'com.example.smarthomz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJYDTDrAHOKBtVVV18bO4C8ubDfyRylRY',
    appId: '1:756197314313:web:f025fb9a3bc0eb347b8dd8',
    messagingSenderId: '756197314313',
    projectId: 'smarthomz-49270',
    authDomain: 'smarthomz-49270.firebaseapp.com',
    storageBucket: 'smarthomz-49270.appspot.com',
    measurementId: 'G-9R051NR6P1',
  );
}
